### ISSUE TITLE
how to retain debug views after debugging finished

### ISSUE THREAD

**Issue by ihshim523** [kiddkai/atom-node-debugger#138]
After debugging finished by error or being terminated, debugging views are closed immediately and couldn't see what was the cause and then no way to open them up again.

**Comment by codecontemplator** [comment]
I think I accidentally introduced this behaviour when implementing the attach behaviour. Maybe the right behaviour is to close the panel automatically only when the user stops the debugger. If the process stops either due to exit or due to errors the panels should probably stay open until they are closed manually.

**Comment by codecontemplator** [comment]
Problem should be fixed in 1.4.5
