### ISSUE TITLE
incorrect working directory using Windows shrotcut

### ISSUE THREAD

**Issue by srankers** [kiddkai/atom-node-debugger#97]
Hi,
create a Windows shortcut for Atom. Specify the working directory (on shortcut -> right click -> properties -> specify Start in: e.g. c:\ ) . Start Atom via shortcut and run a script like:
`console.log("The current working directory is " + process.cwd());`
Notice that a different working directory is shown.
Starting the script in atom using the plugin *script* shows the correct working directory.

Workaround: Start atom in your working directory using command line.

**Comment by codecontemplator** [comment]
Hi,

The current working directory should be set to the folder containing the startup file. In v 1.1.9 this does not work though but it has been fixed in trunk. We have also discussed the possibility to override the default working directory in the config file but that has not been implemented. 

@kiddkai maybe it is time to build a new release soon. If you tell me what to do I can fix it.

**Comment by codecontemplator** [comment]
Fixed in the latest version
